### PR TITLE
made file existence checking compatible

### PR DESCRIPTION
**Pull request by Machiel-B**
Sorry, I missed the check. Your fix didn't do the trick completely, so here's my effort.

### CODE REVIEW

**Comment by Machiel-B** [comment]
Oh, just noticed a bug

**Comment by vitaly-t** [comment]
I tested my changes using various configurations - it all worked. What did I miss?

**Comment by Machiel-B** [comment]
I'm not a grunt expert myself, but based on [this article](http://dontkry.com/posts/code/2013-04-24-use-this-files.html) there could be some issues. I updated my Pull Request, should be alright now.

**Comment by vitaly-t** [comment]
It would be nice to understand what is it we are fixing, before applying the fix, otherwise it is pointless, if the change cannot be tested.

**Comment by vitaly-t** [comment]
@Machiel-B I had another read through that article, and now I understand what it is talking about - the problem of trying to use files through property `this.data`.

But my implementation doesn't do it. I only test `this.data.files` sources when they are specified, to check for files existence, nothing else. This approach does not have any problems.

The processing code itself still uses `this.files` as before, so it will always work. And my tests prove so also.

**Comment by vitaly-t** [comment]
@Machiel-B Your previous PR was invaluable, but for this one, I'm now convinced that the change is not needed, so closing it, sorry.

**Comment by Machiel-B** [comment]
No problem. The grunt file parsing is powerfull, yet complex, and I'm just
starting to wrap my head around it. I'll probably still do some tests to
ease my conscience, but you are right in closing this as it just adds
complexity.

**Comment by vitaly-t** [comment]
Grunt is indeed very powerful. And despite that, its authors abandoned it, it hasn't seen a release in 2 years. Most are moving into gulp instead, for which I have [gulp-decomment](https://github.com/vitaly-t/gulp-decomment) also.

**Pull request closed without merging**
