### PR TITLE
implemented common grunt file patterns

### PR DESCRIPTION
**Pull request by Machiel-B**
Needed to apply this to multiple files at once, so I added support for [common grunt file patterns](http://gruntjs.com/configuring-tasks#files).
Also fixed a bug where the code expected 'method' but the example used 'type' to select a comment type. Now it uses 'type' everywhere.

### CODE REVIEW

**Comment by vitaly-t** [comment]
@Machiel-B Thank you for this PR! I'm shocked that I missed that `method` thing, even after all the testing I've done. Your code looks much cleaner. I just need to figure out the exact changes in the syntax so that documentation is updated accordingly.

Would you, please, give an example of the updated syntax usage, so I can put it into the docs? From the code itself it is not so obvious  for documentation.

**Comment by Machiel-B** [comment]
The old way should still work, but now it also support the other grunt file patterns i.e.

```

   dev:{
        options: {
           type: 'html' 
        },
        files: {
            './.tmp/index.html' : './.tmp/index.html'
        }
    }

    dist:{
        options: {
           type: 'text' 
        },
        src: './src/index.html',
        dest: './build',
    },

    withCwd:{
        options: {
           type: 'text' 
        },
        src:['./*.html', './**/*.html','!./vendor/**/*'], //array style with globs 
        dest: './', //output folder
        cwd: './dist/' //current working directory
    },

```

**Comment by vitaly-t** [comment]
@Machiel-B Thank you! I will update the docs, test it all and release soon.

By the way, I've checked in the code with refactored messages - I hope you will like them ;)

**Comment by vitaly-t** [comment]
@Machiel-B version 0.2.0 has been released.

**Comment by vitaly-t** [comment]
@Machiel-B I noticed only now that the PR did change something in the way old version used to work:

When it couldn't find the source file, it was throwing an error. Now if the source file isn't found, nothing happens, it is just skipped. I'm not sure if this is a good change.

**Comment by vitaly-t** [comment]
@Machiel-B Released 0.2.1, with this corrected - to throw an error on any explicit source file that's not found.

**Pull request merged**
